import Head from 'next/head'
import { Inter } from 'next/font/google'
import { 
  gql, 
  ApolloProvider, 
} from "@apollo/client";
import client from "utils/apollo-client";
import { qAnimeList } from 'utils/query';


const inter = Inter({ subsets: ['latin'] })

export default function Home({anime}) {
  console.log('anime', anime)
  return (
    <>
      <Head>
        <title>Anime World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{height: "100vh"}}><h1>ANIME WORLD</h1></div>
        <div> 
          <ApolloProvider client={client}>
            <div>

            </div>
          </ApolloProvider>
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: qAnimeList,
    variables: {
      page: 1,
      perPage: 10
    }
  });

  return {
    props: {
      anime: data
    },
 };
}
