import Head from 'next/head'
import { ApolloProvider } from "@apollo/client";
import client from "graphql/apollo-client";
import dynamic from 'next/dynamic';

const AnimeList = dynamic(() => import("container/anime-list"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Anime World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div><h1>ANIME WORLD</h1></div>
        <div> 
          <ApolloProvider client={client}>
            <AnimeList />
          </ApolloProvider>
        </div>
      </main>
    </>
  )
}


